/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.GUIpannels;

import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JList;
import Client.NoItemSelectedException;
import Shared.Model.Table;
import javax.swing.*;
import javax.swing.SwingUtilities;
import java.awt.event.ActionEvent;

/**
 *
 * @author Rajtek
 */
public class LobbyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LobbyJPanel
     */
    public void createAddingTableForm() {
        JFrame dialog = new JFrame("Dodaj stół");
        AddingTableJPanel addingPanel = new AddingTableJPanel();
        dialog.getContentPane().add(addingPanel);
        dialog.pack();
        dialog.setResizable(false);
        waitForAction(addingPanel);
        dialog.setVisible(true);
        lockWindow();
    }

    private void lockWindow() {
        SwingUtilities.windowForComponent(this).setEnabled(false);
    }

    private void disposeAndUnlockWindow(AddingTableJPanel panel) {
        SwingUtilities.getWindowAncestor(panel).dispose();
        SwingUtilities.windowForComponent(this).setEnabled(true);
        SwingUtilities.windowForComponent(this).requestFocus();
    }

    private void waitForAction(AddingTableJPanel panel) {
        panel.getjButton1().addActionListener((ActionEvent e) -> {
            disposeAndUnlockWindow(panel);
        });

        panel.getjButton2().addActionListener((ActionEvent e) -> {
            disposeAndUnlockWindow(panel);
        });

    }

    public LobbyJPanel() {
        initComponents();

    }

    public JButton getJoinButton() {
        return joinButton;
    }

    public int getTableID() throws NoItemSelectedException {
//        String s = tablesList.getSelectedValue();
//        if (s == null) {
//            throw new NoItemSelectedException();
//        }
//        s = s.substring(1, 5);
//        s = s.trim();

        if(tablesList.getSelectedValue()==null) throw new NoItemSelectedException();
        
        return tablesList.getSelectedValue().getId();
    }

    public void setLogin(String login) {
        loginLabel.setText("Login: " + login);
    }

    public void setCash(Integer cash) {
        cashLabel.setText("Cash: " + cash.toString());
    }

    public void setTableInfo(String info) {
        tablePlayersLabel.setText(info);
    }

    public JList<Table> getTablesList() {
        return tablesList;
    }

    public void setListModel(AbstractListModel e) {
        tablesList.setModel(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablesList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        cashLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePlayersLabel = new javax.swing.JLabel();
        addTableButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        tablesList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(tablesList);

        loginLabel.setText("Login:");

        cashLabel.setText("Cash:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashLabel)
                    .addComponent(loginLabel))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashLabel)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel1.setText("ID stołu           Blind                                              Graczy/Miejsc");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Dostępne stoły:");

        joinButton.setText("Połącz");
        joinButton.setEnabled(false);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 200));

        tablePlayersLabel.setBackground(new java.awt.Color(250, 250, 250));
        tablePlayersLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tablePlayersLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gacze online:"));
        tablePlayersLabel.setMinimumSize(new java.awt.Dimension(12, 203));
        tablePlayersLabel.setOpaque(true);
        jScrollPane2.setViewportView(tablePlayersLabel);

        addTableButton.setText("Dodaj stół");
        addTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addTableButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(joinButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addTableButton)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableButtonActionPerformed

        createAddingTableForm();
    }//GEN-LAST:event_addTableButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTableButton;
    private javax.swing.JLabel cashLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton joinButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel tablePlayersLabel;
    private javax.swing.JList<Table> tablesList;
    // End of variables declaration//GEN-END:variables

}
