/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.GUIpannels;


import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JList;
import Client.NoItemSelectedException;

/**
 *
 * @author Rajtek
 */
public class LobbyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LobbyJPanel
     */
    public LobbyJPanel() {
        initComponents();
        
        
    }
    
    public JButton getJoinButton() {
        return joinButton;
    }
    public int getTableID() throws NoItemSelectedException{
        String s=tablesList.getSelectedValue();
        if(s==null) throw new NoItemSelectedException();
        s=s.substring(1, 5);
        s=s.trim();
        return Integer.parseInt(s);
    }
    public void setLogin(String login){
        loginLabel.setText("Login: "+login);
    }
    public void setCash(Integer cash){
        cashLabel.setText("Cash: " + cash.toString());
    } 
    public void setTableInfo(String info){
        tablePlayersLabel.setText(info);
    }
    
    public JList<String> getTablesList() {
        return tablesList;
    }
    public void setListModel(AbstractListModel e){
       tablesList.setModel(e);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablesList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        cashLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePlayersLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        tablesList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tablesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "#1   | 150$/300$           | 0/6", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(tablesList);

        loginLabel.setText("Login:");

        cashLabel.setText("Cash:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashLabel)
                    .addComponent(loginLabel))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashLabel)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel1.setText("ID stołu           Blind                                              Graczy/Miejsc");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Dostępne stoły:");

        joinButton.setText("Połącz");
        joinButton.setEnabled(false);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 200));

        tablePlayersLabel.setBackground(new java.awt.Color(250, 250, 250));
        tablePlayersLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tablePlayersLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gacze online:"));
        tablePlayersLabel.setMinimumSize(new java.awt.Dimension(12, 203));
        tablePlayersLabel.setOpaque(true);
        jScrollPane2.setViewportView(tablePlayersLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinButton)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(joinButton)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cashLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton joinButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel tablePlayersLabel;
    private javax.swing.JList<String> tablesList;
    // End of variables declaration//GEN-END:variables
    
    
}
