/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.GUIpannels;

import javax.swing.AbstractListModel;
import javax.swing.JButton;
import Client.NoItemSelectedException;
import javax.swing.*;
import javax.swing.SwingUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Rajtek
 */
public class LobbyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LobbyJPanel
     */
    public void createAddingRoomForm() {
        JFrame dialog = new JFrame("Dodaj pokój");
        AddingRoomJPanel addingPanel = new AddingRoomJPanel();
        dialog.getContentPane().add(addingPanel);
        dialog.pack();
        dialog.setResizable(false);
        waitForAction(addingPanel);
        dialog.setVisible(true);
        lockWindow();
    }

    private void lockWindow() {
        SwingUtilities.windowForComponent(this).setEnabled(false);
    }

    private void disposeAndUnlockWindow(AddingRoomJPanel panel) {
        SwingUtilities.getWindowAncestor(panel).dispose();
        SwingUtilities.windowForComponent(this).setEnabled(true);
        SwingUtilities.windowForComponent(this).requestFocus();
    }

    private void waitForAction(AddingRoomJPanel panel) {
        panel.getjButton1().addActionListener((ActionEvent e) -> {
            disposeAndUnlockWindow(panel);
        });

        panel.getjButton2().addActionListener((ActionEvent e) -> {
            disposeAndUnlockWindow(panel);
        });

    }

    public LobbyJPanel() {
        initComponents();

    }
    
    public void addJoinListener(ActionListener listenForJoinButton) {
        joinButton.addActionListener(listenForJoinButton);
    }
    
    public void setJoinButtonEnabled(boolean b){
        joinButton.setEnabled(b);
    }


    public int getRoomID() throws NoItemSelectedException {
//        String s = tablesList.getSelectedValue();
//        if (s == null) {
//            throw new NoItemSelectedException();
//        }
//        s = s.substring(1, 5);
//        s = s.trim();

        if(roomsList.getSelectedValue()==null) throw new NoItemSelectedException();
        
        return roomsList.getSelectedValue().getId();
    }

    public void setLogin(String login) {
        loginLabel.setText("Login: " + login);
    }



    public void setRoomInfo(String info) {
        rommUsersLabel.setText(info);
    }
    public void setListModel(AbstractListModel m){
        roomsList.setModel(m);
    }
    public void refreshList(){
        roomsList.ensureIndexIsVisible(0);
    }
    
    public void addListListener(ListSelectionListener l){
        roomsList.addListSelectionListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        roomsList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rommUsersLabel = new javax.swing.JLabel();
        addRoomButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        roomsList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(roomsList);

        loginLabel.setText("Login:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(loginLabel)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jLabel1.setText("ID pokoju                                                           Użytkownicy/Miejsc");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Dostępne pokoje:");

        joinButton.setText("Połącz");
        joinButton.setEnabled(false);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 200));

        rommUsersLabel.setBackground(new java.awt.Color(250, 250, 250));
        rommUsersLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rommUsersLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Użytkownicy online:"));
        rommUsersLabel.setMinimumSize(new java.awt.Dimension(12, 203));
        rommUsersLabel.setOpaque(true);
        jScrollPane2.setViewportView(rommUsersLabel);

        addRoomButton.setText("Dodaj pokój");
        addRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addRoomButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(joinButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addRoomButton)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed

        createAddingRoomForm();
    }//GEN-LAST:event_addRoomButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton joinButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel rommUsersLabel;
    private javax.swing.JList<Shared.Model.Room> roomsList;
    // End of variables declaration//GEN-END:variables

}
