/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.GUIpannels;

import Shared.Model.Player;

/**
 *
 * @author Rajtek
 */
public class PlayerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PlayerJPanel() {
        initComponents();
        
        setBack();
    }

    public void setNumber(int i) {
        jLabel1.setText(Integer.toString(i));
    }

    public void setFirstCard(String path) {
        firstCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + path)));
    }

    public void setSecoundCard(String path) {
        secoundCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + path)));
    }

    public void setBack() {
        firstCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/back.png")));
        secoundCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/back.png")));
    }

    public void setPlayer(Player player) {
        if (player != null) {
            playerLabel.setText(player.getLogin());
            setCash(player.getCash());
            this.setVisible(true);
            System.out.println(player.getLogin());
        }
        
    }

    @Override
    public void setVisible(boolean b) {
        cashLabel.setVisible(b);
        firstCardLabel.setVisible(b);
        jLabel1.setVisible(b);
        playerLabel.setVisible(b);
        secoundCardLabel.setVisible(b);
    }

    public void setCash(int cash) {
        cashLabel.setText(Integer.toString(cash));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secoundCardLabel = new javax.swing.JLabel();
        firstCardLabel = new javax.swing.JLabel();
        playerLabel = new javax.swing.JLabel();
        cashLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setPreferredSize(new java.awt.Dimension(128, 133));

        secoundCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/back.png"))); // NOI18N

        firstCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/back.png"))); // NOI18N

        playerLabel.setText("Rajtek");

        cashLabel.setText("cash: 25 000$");

        jLabel1.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(firstCardLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secoundCardLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(cashLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secoundCardLabel)
                    .addComponent(firstCardLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cashLabel;
    private javax.swing.JLabel firstCardLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JLabel secoundCardLabel;
    // End of variables declaration//GEN-END:variables
}
