/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.GUIpannels;

import Shared.Model.Card;
import Shared.Model.Player;
import Shared.Model.Table;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;

/**
 *
 * @author Rajtek
 */
public class TableJPanel extends javax.swing.JPanel {

    /**
     *
     * Creates new form TablePanel
     */
    PlayerJPanel[] playerJPanelList = new PlayerJPanel[10];
    JLabel[] tableCards = new JLabel[5];
    Table table;
    public TableJPanel() {
        initComponents();

        JLayeredPane jLayeredPane = new JLayeredPane();

        jLayeredPane.add(tableLabel, 4);
        jLayeredPane.add(cardsJPanel, 1);
        jLayeredPane.setSize(440, 256);
        jLayeredPane1.setSize(440, 256);
        jLayeredPane.setVisible(true);

        tableCards[0] = (card1);
        tableCards[1] = (card2);
        tableCards[2] = (card3);
        tableCards[3] = (card4);
        tableCards[4] = (card5);

        playerJPanelList[0] = (playerJPanel1);
        playerJPanelList[1] = (playerJPanel2);
        playerJPanelList[2] = (playerJPanel3);
        playerJPanelList[3] = (playerJPanel4);
        playerJPanelList[4] = (playerJPanel5);
        playerJPanelList[5] = (playerJPanel6);
        playerJPanelList[6] = (playerJPanel7);
        playerJPanelList[7] = (playerJPanel8);
        playerJPanelList[8] = (playerJPanel9);
        playerJPanelList[9] = (playerJPanel10);

        for (PlayerJPanel playerJPanel : playerJPanelList) {
            playerJPanel.setVisible(false);
        }
        hideCards();

    }

    public JFormattedTextField getCallTextField() {
        return callTextField;
    }

    public JButton getCallButton() {
        return callButton;
    }

    public JButton getCheckButton() {
        return checkButton;
    }

    public JButton getFoldButton() {
        return foldButton;
    }

    public void setPlayers(Player[] players) {

        for (int i = 0; i < 10; i++) {
            if (players[i] == null) {
                playerJPanelList[i].setVisible(false);
            } else {
                playerJPanelList[i].setNumber(i + 1);
                playerJPanelList[i].setPlayer(players[i]);
                playerJPanelList[i].setVisible(true);
            }
        }

    }
    public void refreshTable(Table table){
        setPlayers(table.getPlayers());
        setButtonsEnabled(table.isGameStarted());
    }
    public void setButtonsEnabled(boolean b) {
        callButton.setEnabled(b);
        callTextField.setEnabled(b);
        foldButton.setEnabled(b);
        checkButton.setEnabled(b);

    }

    public void hideCards() {
        for (JLabel card : tableCards) {
            card.setVisible(false);
        }
    }

    public void setNextCard(Card card) {
        for (int i = 0; i < 5; i++) {
            if (!tableCards[i].isVisible()) {
                tableCards[i].setVisible(true);
                tableCards[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + card.getPath())));

                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        tableLabel = new javax.swing.JLabel();
        cardsJPanel = new javax.swing.JPanel();
        card1 = new javax.swing.JLabel();
        card2 = new javax.swing.JLabel();
        card3 = new javax.swing.JLabel();
        card4 = new javax.swing.JLabel();
        card5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        foldButton = new javax.swing.JButton();
        callButton = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        callTextField = new javax.swing.JFormattedTextField();
        playerJPanel1 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel2 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel3 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel4 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel5 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel6 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel7 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel8 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel9 = new Client.GUIpannels.PlayerJPanel();
        playerJPanel10 = new Client.GUIpannels.PlayerJPanel();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 256));

        tableLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N

        cardsJPanel.setOpaque(false);
        cardsJPanel.setPreferredSize(new java.awt.Dimension(791, 631));

        card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/2_of_clubs.png"))); // NOI18N

        card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/2_of_clubs.png"))); // NOI18N

        card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/2_of_clubs.png"))); // NOI18N

        card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/2_of_clubs.png"))); // NOI18N

        card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/2_of_clubs.png"))); // NOI18N

        javax.swing.GroupLayout cardsJPanelLayout = new javax.swing.GroupLayout(cardsJPanel);
        cardsJPanel.setLayout(cardsJPanelLayout);
        cardsJPanelLayout.setHorizontalGroup(
            cardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsJPanelLayout.createSequentialGroup()
                .addComponent(card1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card5))
        );
        cardsJPanelLayout.setVerticalGroup(
            cardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card1)
            .addComponent(card2)
            .addComponent(card3)
            .addComponent(card4)
            .addComponent(card5)
        );

        foldButton.setText("fold");
        foldButton.setEnabled(false);

        callButton.setText("call");
        callButton.setEnabled(false);

        checkButton.setText("check");
        checkButton.setEnabled(false);

        callTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        callTextField.setText("0");
        callTextField.setEnabled(false);
        callTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                callTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(callButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(callTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(checkButton)
            .addComponent(foldButton)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(checkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foldButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(callButton)
                    .addComponent(callTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(tableLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cardsJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(tableLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 58, Short.MAX_VALUE)
                    .addComponent(cardsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 58, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tableLabel))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 84, Short.MAX_VALUE)
                    .addComponent(cardsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 85, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(playerJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerJPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(playerJPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerJPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerJPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerJPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerJPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerJPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerJPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void callTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_callTextFieldKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_callTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton callButton;
    private javax.swing.JFormattedTextField callTextField;
    private javax.swing.JLabel card1;
    private javax.swing.JLabel card2;
    private javax.swing.JLabel card3;
    private javax.swing.JLabel card4;
    private javax.swing.JLabel card5;
    private javax.swing.JPanel cardsJPanel;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton foldButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private Client.GUIpannels.PlayerJPanel playerJPanel1;
    private Client.GUIpannels.PlayerJPanel playerJPanel10;
    private Client.GUIpannels.PlayerJPanel playerJPanel2;
    private Client.GUIpannels.PlayerJPanel playerJPanel3;
    private Client.GUIpannels.PlayerJPanel playerJPanel4;
    private Client.GUIpannels.PlayerJPanel playerJPanel5;
    private Client.GUIpannels.PlayerJPanel playerJPanel6;
    private Client.GUIpannels.PlayerJPanel playerJPanel7;
    private Client.GUIpannels.PlayerJPanel playerJPanel8;
    private Client.GUIpannels.PlayerJPanel playerJPanel9;
    private javax.swing.JLabel tableLabel;
    // End of variables declaration//GEN-END:variables
}
